apiVersion: v1
kind: Service
metadata:
  name: tofu-sample-app
spec:
  type: NodePort
  selector:
    app: tofu-sample-app
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 3000
